version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    volumes:
      - ./etc:/etc
    environment:
      DATABASE_PATH: /etc/database.db
      PORT: 7777